version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "release-note-none"
    - "kind/misc"